version: '3.9'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    command: ["npm", "start"]
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000

  # Backend Service
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/palace_of_goods
      - SECRET_KEY=your-secret-key
      - JWT_SECRET_KEY=your-jwt-secret-key
    volumes:
      - ./backend:/app
    depends_on:
      - db

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: palace_of_goods
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  # Nginx Reverse Proxy
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  pgdata:
