name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Backend
        run: python -c "from tests.e2e import setup_backend, start_backend; setup_backend(); process = start_backend()"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Stop Backend
        run: python -c "from tests.e2e import stop_backend; stop_backend(process)"
